# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# XDC: imports/rtl_ddr3_src/urbana_ddr3.xdc

# IP: ip/THE_WRAM/THE_WRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==THE_WRAM || ORIG_REF_NAME==THE_WRAM} -quiet] -quiet

# XDC: c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/THE_WRAM/THE_WRAM_ooc.xdc
