# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.runs/synth_1/emu.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.cache/wt [current_project]
set_property parent.project_path C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/hdmi_tx_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/chip/CX4/drom.mif
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/chip/BSX/bsx121-124.mif
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/chip/DSP/dsp11b23410_p.mif
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/chip/DSP/dsp11b23410_d.mif
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/new/bram.sv
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/sys/hq2x.sv
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/ioport.sv
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/sdram.sv
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/sys/video_freezer.sv
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/SNES.sv
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/rtl_ddr3_src/hex_driver.sv
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/rtl_ddr3_src/rtl_ddr3_top.sv
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/rtl_ddr3_src/ram_reader.sv
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/rtl_ddr3_src/sdcard_init.sv
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/new/ddr3_helper.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/main.v
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/sys/scandoubler.v
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/65C816/P65816_pkg.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/65C816/BCDAdder.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/65C816/AddSubBCD.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/65C816/ALU.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SPC700/SPC700_pkg.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SPC700/AddSub.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SPC700/BCDAdj.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SPC700/ALU.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/65C816/AddrGen.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SPC700/AddrGen.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/CEGen.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/65C816/MCode.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/65C816/P65C816.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/CPU.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/DSP_PKG.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/DSP.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SPC700/MCode.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SPC700/MulDiv.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/PPU_PKG.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/PPU.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SPC700/SPC700.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SMP.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SWRAM.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/SNES.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/chip/GSU/GSU_PKG.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/rtl/chip/SPC7110/SPC7110_DEC_PKG.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/smpsim/aram.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/SNES_MiSTer-master/smpsim/audio.vhd
}
read_vhdl -library xil_defaultlib {
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/rtl_ddr3_src/SDCard.vhd
  C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/imports/rtl_ddr3_src/Common.vhd
}
read_ip -quiet C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/ip/THE_WRAM/THE_WRAM.xci
set_property used_in_implementation false [get_files -all c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/THE_WRAM/THE_WRAM_ooc.xdc]

read_ip -quiet C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/ip/vram/vram.xci
set_property used_in_implementation false [get_files -all c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/vram/vram_ooc.xdc]

read_ip -quiet C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/ip/Audio_RAM/Audio_RAM.xci
set_property used_in_implementation false [get_files -all c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/Audio_RAM/Audio_RAM_ooc.xdc]

read_ip -quiet C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/ip/CGRAM/CGRAM.xci
set_property used_in_implementation false [get_files -all c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/CGRAM/CGRAM_ooc.xdc]

read_ip -quiet C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/constrs_1/new/constraints.xdc]

read_xdc C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/constrs_1/imports/rtl_ddr3_src/urbana_ddr3.xdc
set_property used_in_implementation false [get_files C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/constrs_1/imports/rtl_ddr3_src/urbana_ddr3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/theox/Desktop/project_8_1.xpr/project_8_1.xpr/project_8/project_8.srcs/utils_1/imports/synth_1/main.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top emu -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef emu.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file emu_utilization_synth.rpt -pb emu_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
