# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/karans4/Desktop/project_8_1.xpr/project_8/project_8.srcs/sources_1/ip/Audio_RAM/Audio_RAM.xci
# IP: The module: 'Audio_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/karans4/Desktop/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/Audio_RAM/Audio_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Audio_RAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/karans4/Desktop/project_8_1.xpr/project_8/project_8.srcs/sources_1/ip/Audio_RAM/Audio_RAM.xci
# IP: The module: 'Audio_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/karans4/Desktop/project_8_1.xpr/project_8/project_8.gen/sources_1/ip/Audio_RAM/Audio_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Audio_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
